Fix for flapping CSV Import test
We are experiencing periodic test failures
>Tenejo::CsvImporter calls modules - FLAKY
>spec.lib.tenejo.csv_importer_spec
>spec/lib/tenejo/csv_importer_spec.rb

```
Failure/Error: return if work.id && work&.thumbnail_id && work&.representative_id

NoMethodError:
  undefined method `id' for nil:NilClass
./app/lib/tenejo/csv_importer.rb:57:in `ensure_thumbnails'
```

Since that section of code shouldn't be called without a valid work, add a check
and log an error and return instead of raising an unhandled error.